apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.instanceName }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.instanceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.instanceName }}
    spec:
      containers:
      - name: http-echo
        image: http-echo:local
        args:
        - "-text=I am from {{ .Values.instanceName }}"
        ports:
        - containerPort: 5678