apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.instanceName }}
spec:
  selector:
    app: {{ .Values.instanceName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678
  type: NodePort