# bar-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bar
  template:
    metadata:
      labels:
        app: bar
    spec:
      containers:
      - name: http-echo
        image: http-echo:local
        args:
        - "-text=I am from bar"
        ports:
        - containerPort: 5678