# foo-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
      - name: http-echo
        image: http-echo:local
        args:
        - "-text=I am from foo"
        ports:
        - containerPort: 5678