name: Kind kubernetes Project

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.16.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Create Kubernetes Cluster
        run: |
          kind create cluster --config kind-cluster.yaml
          kubectl get nodes

      - name: Set up docker image and load to kind
        run: |
          sh  ./scripts/image.sh
          docker images
          kind load docker-image http-echo:local --name kind            
