name: Kind kubernetes Project

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'
      - name: Install and Start SSH Server
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server
          sudo mkdir /var/run/sshd
          echo 'root:$(openssl rand -base64 12)' | sudo chpasswd # Set a random password
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo service ssh start

      - name: Print SSH details
        run: |
          echo "SSH Server running on port 22"
          echo "Password: $(openssl rand -base64 12)" # Note: You should capture this password and use it to connect
          echo "Use SSH to connect: ssh root@$(curl ifconfig.me) -p 22"
          
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.16.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Create Kubernetes Cluster
        run: |
          kind create cluster --config kind-cluster.yaml
          kubectl get nodes

      - name: Set up docker image and load to kind
        run: |
          sh  ./scripts/image.sh
          docker images
          kind load docker-image http-echo:local --name kind            
      
      - name: Deploying Nginix Ingress Controller
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update
          helm install ingress-nginx ingress-nginx/ingress-nginx --namespace ingress-nginx --create-namespace
      
      - name: Deploying Foo/Bar Services
        run: |
          kubectl apply -f ./deployment/foo-deployment.yaml
          kubectl apply -f ./deployment/bar-deployment.yaml
          kubectl apply -f ./services/foo-service.yaml
          kubectl apply -f ./services/bar-service.yaml
          kubectl rollout status deployment.apps/foo
          kubectl rollout status deployment.apps/bar
          kubectl get pods
          kubectl get svc
      
      - name: Deploying Ingress Service
        run: | 
          kubectl cluster-info --context kind-kind
          kubectl apply --dry-run=client -f ./ingress/ingress.yaml

      - name: Get API server logs
        run: |
          kubectl logs -n kube-system -l component=kube-apiserver

      - name: Get API server logs
        run: |
          kubectl logs -n kube-system -l component=kube-apiserver

      - name: Wait for cluster to be ready
        run: kubectl wait --for=condition=Ready node --all --timeout=90s

      - name: Set kubectl context
        run: |
          kubectl cluster-info --context kind-kind
          kubectl get validatingwebhookconfigurations 

      - name: Deploy Ingress manifest
        run: |
          kubectl apply -f ingress/ingress.yaml

      - name: Check Ingress resources
        run: |
          kubectl get ingress --all-namespaces
          kubectl describe ingress --all-namespaces

      - name: Check services
        run: kubectl get svc --all-namespaces

      - name: Check Ingress controller pods
        run: kubectl get pods -n kube-system

      - name: Verify Ingress deployment
        run: |
          kubectl get ingress --all-namespaces
          kubectl describe ingress --all-namespaces