name: Kind kubernetes Project

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.16.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Create Kubernetes Cluster
        run: |
          kind create cluster --config kind-cluster.yaml
          kubectl get nodes

      - name: Set up docker image and load to kind
        run: |
          sh  ./scripts/image.sh
          docker images
          kind load docker-image http-echo:local --name kind            
      
      - name: Deploying Nginix Ingress Controller
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update
          helm install ingress-nginx ingress-nginx/ingress-nginx --namespace ingress-nginx --create-namespace
      
      - name: Deploying Foo/Bar Services
        run: |
          kubectl apply -f ./deployment/foo-deployment.yaml
          kubectl apply -f ./deployment/bar-deployment.yaml
          kubectl apply -f ./services/foo-service.yaml
          kubectl apply -f ./services/bar-service.yaml
          kubectl rollout status deployment.apps/foo
          kubectl rollout status deployment.apps/bar
          kubectl get pods
          kubectl get svc
      
      - name: Deploying Ingress Service
        run: | 
          kubectl cluster-info --context kind-kind
          kubectl apply -f ./ingress/ingress.yaml
          kubectl get pods -n ingress-nginx
          kubectl get services -n ingress-nginx

      
     

  
       