name: Kind kubernetes Project

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    #runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'


      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1

      - name: Create Kubernetes Cluster
        run: |
          kind create cluster --config kind-cluster.yaml
          kubectl get nodes

      - name: Set up docker image and load to kind
        run: |
          sh  ./scripts/image.sh
          docker images
          kind load docker-image http-echo:local --name kind            
      
      - name: Deploying Nginix Ingress Controller
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update
          helm install ingress-nginx ingress-nginx/ingress-nginx --namespace ingress-nginx --create-namespace
          kubectl get svc -n ingress-nginx
          

      
      - name: Deploying Foo/Bar Services
        run: |
          kubectl apply -f ./deployment/foo-deployment.yaml
          kubectl apply -f ./deployment/bar-deployment.yaml
          kubectl apply -f ./services/foo-service.yaml
          kubectl apply -f ./services/bar-service.yaml
          kubectl rollout status deployment.apps/foo
          kubectl rollout status deployment.apps/bar
          kubectl get pods
          kubectl get svc
      
     

      - name: Deploy Ingress manifest
        run: |
          kubectl delete -A ValidatingWebhookConfiguration ingress-nginx-admission
          kubectl apply -f ingress/ingress.yaml

      - name: Check Ingress resources
        run: |
          kubectl get ingress --all-namespaces
          kubectl describe ingress --all-namespaces

      - name: Check services
        run: kubectl get svc --all-namespaces

      - name: Check Ingress controller pods
        run: kubectl get pods -n kube-system

      - name: Verify Ingress deployment
        run: |
          kubectl get ingress --all-namespaces
          kubectl describe ingress --all-namespaces
      
     
      - name: Add k6 GPG key
        run: |
          wget -qO - https://dl.k6.io/key.gpg  | sudo apt-key add -
          echo "deb [arch=amd64] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
         
      - name: Install k6
        run: |
          sudo apt-get update
          sudo apt-get install -y k6

      - name: Run load test
        run: |
          kubectl port-forward service/foo-service 8080:80 &
          kubectl port-forward service/bar-service 8081:80 &
          sleep 10
          k6 run ./scripts/load-test.js

      - name: Upload load testing results
        uses: actions/upload-artifact@v3
        with:
          name: k6-results
          path: ./scripts/results.json